# Generated by Django 4.2 on 2024-03-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
