# Generated by Django 4.2 on 2024-03-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='customers',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
