# Generated by Django 4.2 on 2024-04-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
