# Generated by Django 5.1 on 2024-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_options_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['image_order']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Cashew', 'Cashew'), ('Almond', 'Almond'), ('Cardamom', 'Cardamom'), ('Combo', 'Combo')], max_length=100, null=True),
        ),
    ]
