# Generated by Django 4.2 on 2024-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('Cashew', 'Cashew'), ('Almond', 'Almond'), ('Pista', 'Pista'), ('Dates', 'Dates'), ('Assorted', 'Assorted'), ('Combo', 'Combo')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
