# Generated by Django 5.1 on 2024-12-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_options_productimage_image_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_order',
        ),
    ]
