# Generated by Django 4.2 on 2024-03-10 13:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_type_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
