# Generated by Django 4.2 on 2024-03-10 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='specification',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
