# Generated by Django 5.1 on 2024-12-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('Cashew', 'Cashew'), ('Almond', 'Almond'), ('Cardamom', 'Cardamom'), ('Combo', 'Combo')], max_length=100, null=True),
        ),
    ]
