# Generated by Django 5.1 on 2024-12-06 05:18

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pack', models.CharField(blank=True, max_length=100, null=True)),
                ('img1', models.ImageField(upload_to='Products/')),
                ('img2', models.ImageField(upload_to='Products/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='Products/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('Cashew', 'Cashew'), ('Almond', 'Almond'), ('Cardamom', 'Cardamom'), ('Combo', 'Combo')], max_length=100, null=True)),
                ('stock', models.BooleanField(default=True)),
                ('qty', models.CharField(blank=True, max_length=5, null=True)),
                ('qcheck', models.CharField(blank=True, max_length=5, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('specification', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.product'),
        ),
    ]
