# Generated by Django 5.1 on 2024-12-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_product_delete_products_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img4',
        ),
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Products/Videos/'),
        ),
    ]
