# Generated by Django 5.1 on 2024-12-07 04:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_img4_category_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Cashew', 'Cashew'), ('Almond', 'Almond'), ('Cardamom', 'Cardamom'), ('Combo', 'Combo')], max_length=100, null=True)),
                ('title', models.CharField(max_length=150, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('stock', models.BooleanField(default=True, null=True)),
                ('qty', models.CharField(max_length=5, null=True)),
                ('qcheck', models.CharField(max_length=5, null=True)),
                ('shortD', models.TextField(null=True)),
                ('discription', ckeditor.fields.RichTextField(null=True)),
                ('specification', ckeditor.fields.RichTextField(null=True)),
                ('img1', models.ImageField(upload_to='Products/')),
                ('img2', models.ImageField(upload_to='Products/')),
                ('img3', models.ImageField(blank=True, upload_to='Products/')),
                ('img4', models.ImageField(blank=True, upload_to='Products/')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
