# Generated by Django 5.1 on 2024-12-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_delete_category_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='qcheck',
        ),
    ]
